name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t eks-dev .

    - name: Tag Docker Image
      run: |
        docker tag eks-dev 300724398447.dkr.ecr.us-east-1.amazonaws.com/eks-dev

    - name: Push Docker Image
      run: |
        docker push 300724398447.dkr.ecr.us-east-1.amazonaws.com/eks-dev
